#!/usr/bin/env bash
set -e

URL="https://telegram.org/dl/desktop/linux"
INSTALL_DIR="/opt/telegram"
BIN_LINK="/usr/local/bin/telegram-desktop"
TMP_DIR="/tmp/telegram-install"
DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/telegram-desktop.desktop"

# Prepare temporary workspace
sudo rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR"

echo "Downloading Telegram Desktop..."
wget -q "$URL" -O telegram.tar.xz

echo "Extracting package..."
tar -xf telegram.tar.xz

echo "Installing to $INSTALL_DIR..."
sudo rm -rf "$INSTALL_DIR"
sudo mv Telegram "$INSTALL_DIR"

# Create a symlink for command-line use
sudo ln -sf "$INSTALL_DIR/Telegram" "$BIN_LINK"

# Create desktop entry
mkdir -p "$DESKTOP_DIR"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Name=Telegram Desktop
Comment=Fast and secure messaging
TryExec=$BIN_LINK
Exec=$BIN_LINK -- %u
Icon=$INSTALL_DIR/telegram.png
Terminal=false
StartupWMClass=TelegramDesktop
Type=Application
Categories=Chat;Network;InstantMessaging;Qt;
MimeType=x-scheme-handler/tg;x-scheme-handler/tonsite;
Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
Actions=quit;
DBusActivatable=true
SingleMainWindow=true
X-GNOME-UsesNotifications=true
X-GNOME-SingleWindow=true

[Desktop Action quit]
Exec=$BIN_LINK -quit
Name=Quit Telegram
Icon=application-exit
EOF

# Remove duplicate .desktop entries generated by Telegram
echo "Cleaning up duplicate Telegram desktop entries..."
find "$DESKTOP_DIR" -type f -name "org.telegram.desktop.*.desktop" -delete 2>/dev/null || true
find "$DESKTOP_DIR" -type f -name "rg.telegram.desktop.*.desktop" -delete 2>/dev/null || true

# Update desktop database if available
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$DESKTOP_DIR" || true
fi

echo "Telegram Desktop installed successfully."
echo "You can start it by running: telegram-desktop"
